itapps/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('itreporting/', include('itreporting.urls')),
]

itreporting/urls.py
from django.urls import path
from . import views

app_name ='itreporting'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

itreporting/models.py
from django.db import models

# Create your models here.

itreporting/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def home(Request):
    return render(Request, 'itreporting/home.html', {'title': 'Welcome'})

def about(Request):
    return HttpResponse('<h1>Student IT Services About</h1>')

def contact(Request):
    return HttpResponse('<h1>Student IT Services Contact</h1>')

itreporting/templates/itreporting/about.html
{% extends "itreporting/base.html" %}
{% block content %}
<h1>Welcome to the about page</h1>
{% endblock %}

itreporting/templates/itreporting/base.html
{% load static%}
<!DOCTYPE html>
<html>
    <head>
    <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-
        QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" /
        >

        <title>Student IT Services - {{title}}</title>
    </head>

    <body>
        <div class="container">
            <header class="site-header">
                <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                    <div class="container">
                    <a class="navbar-brand mr-4" href="{% url 'itreporting:home' %}">Student IT
                    Services</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-
                        target="#navbarToggle"
                        aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle
                        navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{% url 'itreporting:home' %}">Home</a>
                            <a class="nav-item nav-link" href="{% url 'itreporting:about' %}">About</a>
                            <a class="nav-item nav-link" href="#">Report</a>
                            <a class="nav-item nav-link" href="{% url 'itreporting:contact' %}">Contact</a>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            <a class="nav-item nav-link" href="#">Login</a>
                            <a class="nav-item nav-link" href="#">Register</a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <div class="row">
            <div class="col-md-8">
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>General Information</h3>
                <p class='text-muted'>Lorem ipsum dolor sit amet, iudico docendi inciderint per
                eu, ea vis scripta senserit periculis.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Issues Reported</li>
                        <li class="list-group-item list-group-item-light">IT Policies</li>
                        <li class="list-group-item list-group-item-light">IT Regulations</li>
                        <li class="list-group-item list-group-item-light">Upcoming Events</li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
integrity="sha384-
I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
integrity="sha384-
0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
crossorigin="anonymous"></script></body>

</html>

itreporting/templates/itreporting/contact.html
{% extends "itreporting/base.html" %}
{% block content %}
<h1>Welcome to the contact page</h1>
{% endblock %}

itreporting/templates/itreporting/home.html
{% extends "itreporting/base.html" %}
{% block content %}
<h1>Welcome to the homepage</h1>
{% endblock %}